name: OWASP ZAP DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Opcional: instala dependencias o configura el entorno de prueba
      - name: Set up test environment
        run: |
          npm install
          npm run build
          docker-compose up -d  # Usa esto si tienes un entorno de prueba en Docker

      # Ejecuta OWASP ZAP en un contenedor Docker
      - name: Start OWASP ZAP
        run: |
          docker run -d --name zap \
            -p 8080:8080 \
            owasp/zap2docker-stable zap-webswing.sh

      # Escanea la aplicación usando OWASP ZAP
      - name: Perform DAST scan
        run: |
          docker exec zap zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html

      # Carga el informe generado como un artefacto
      - name: Upload DAST report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      # Opcional: Detiene y elimina el contenedor de OWASP ZAP
      - name: Clean up
        run: |
          docker stop zap
          docker rm zap
