name: OWASP ZAP DAST

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dast-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Limpiar e instalar dependencias, resolviendo conflictos
      - name: Set up dependencies
        run: |
          echo "Cleaning node_modules and lockfile..."
          rm -rf node_modules package-lock.json
          echo "Installing dependencies with --legacy-peer-deps..."
          npm install --legacy-peer-deps

      # Asegurar versiones específicas de TypeScript y ts-jest
      - name: Force compatible dependency versions
        run: |
          echo "Installing specific versions of TypeScript and ts-jest..."
          npm install typescript@4.9.5 ts-jest@26.5.6 --save-dev

      # Validar y ajustar tsconfig.json si es necesario
      - name: Ensure tsconfig.json compatibility
        run: |
          if ! grep -q '"skipLibCheck": true' tsconfig.json; then
            echo "Adding 'skipLibCheck' to tsconfig.json..."
            sed -i '/"compilerOptions": {/a \ \ \ \ "skipLibCheck": true,' tsconfig.json
          fi

      # Construir el proyecto
      - name: Build the project
        run: npm run build

      # Configurar el entorno de prueba si es necesario
      - name: Set up test environment
        run: |
          docker-compose up -d  # Usa esto si tienes un entorno de prueba en Docker

      # Ejecutar OWASP ZAP
      - name: Start OWASP ZAP
        run: |
          docker run -d --name zap \
            -p 8080:8080 \
            owasp/zap2docker-stable zap-webswing.sh

      # Escanear la aplicación
      - name: Perform DAST scan
        run: |
          docker exec zap zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html

      # Subir el reporte
      - name: Upload DAST report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      # Detener y limpiar el contenedor
      - name: Clean up
        run: |
          docker stop zap
          docker rm zap
