name: OWASP ZAP Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      # Configurar el repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurar Node.js (opcional si necesitas levantar tu aplicación con Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependencias y levantar el servidor
      - name: Install Dependencies
        run: |
          npm install
      - name: Start Server
        run: |
          nohup npm start &
          sleep 10 # Espera a que el servidor inicie

      # Ejecutar OWASP ZAP en Docker
      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://localhost:3000' # Cambia por la URL de tu aplicación
          rules_file_name: '.zap/rules.json' # Opcional: Configura reglas personalizadas
          report_format: 'HTML' # Formato de reporte
          cmd_options: '-config api.disablekey=true'

      # Cargar los resultados del escaneo
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: owasp-zap-report.html
