name: OWASP ZAP DAST

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dast-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar dependencias y limpiar cualquier instalación previa
      - name: Set up dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      # Validar si existe el script build, si no, configurar uno temporal
      - name: Ensure build script exists
        run: |
          if ! grep -q '"build"' package.json; then
            echo 'Adding temporary build script to package.json'
            sed -i '/"scripts": {/a \ \ \ \ "build": "echo No build script provided",' package.json
          fi

      # Ejecutar el build del proyecto
      - name: Build the project
        run: npm run build

      # Iniciar el entorno de prueba si es necesario
      - name: Set up test environment
        run: |
          docker-compose up -d  # Usa esto si tienes un entorno de prueba en Docker

      # Ejecuta OWASP ZAP en un contenedor Docker
      - name: Start OWASP ZAP
        run: |
          docker run -d --name zap \
            -p 8080:8080 \
            owasp/zap2docker-stable zap-webswing.sh

      # Escanea la aplicación usando OWASP ZAP
      - name: Perform DAST scan
        run: |
          docker exec zap zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html

      # Carga el informe generado como un artefacto
      - name: Upload DAST report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      # Opcional: Detiene y elimina el contenedor de OWASP ZAP
      - name: Clean up
        run: |
          docker stop zap
          docker rm zap
