name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Baseline ZAP Scan
    steps:
      # Clonar el repositorio
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Limpiar el sistema Docker (opcional, para evitar conflictos)
      - name: Clean Docker System
        run: docker system prune -af

      # Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Escaneo Baseline de ZAP
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000' # Cambia según tu aplicación
          rules_file_name: '.zap/rules.tsv' # Archivo de reglas opcional
          cmd_options: '-a -j'

      # Cargar el reporte como artefacto
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-baseline-report
          path: zap.out
