name: OWASP ZAP DAST with TypeScript Fix

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dast-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar dependencias y corregir problemas con TypeScript y lodash
      - name: Set up dependencies and fix TypeScript issues
        run: |
          echo "Cleaning node_modules and lockfile..."
          rm -rf node_modules package-lock.json

          echo "Installing dependencies with fixed versions..."
          npm install
          npm install typescript@latest --save-dev
          npm install @types/lodash@latest --save-dev

      # Validar y ajustar tsconfig.json si es necesario
      - name: Ensure tsconfig.json compatibility
        run: |
          if ! grep -q '"skipLibCheck": true' tsconfig.json; then
            echo "Adding 'skipLibCheck' to tsconfig.json..."
            sed -i '/"compilerOptions": {/a \ \ \ \ "skipLibCheck": true,' tsconfig.json
          fi

      # Construir el proyecto para detectar errores
      - name: Build the project
        run: npm run build

      # Iniciar el entorno de prueba si es necesario
      - name: Set up test environment
        run: |
          docker-compose up -d  # Usa esto si tienes un entorno de prueba en Docker

      # Ejecutar OWASP ZAP en un contenedor Docker
      - name: Start OWASP ZAP
        run: |
          docker run -d --name zap \
            -p 8080:8080 \
            owasp/zap2docker-stable zap-webswing.sh

      # Escanear la aplicación usando OWASP ZAP
      - name: Perform DAST scan
        run: |
          docker exec zap zap-baseline.py \
            -t http://localhost:8080 \
            -r zap_report.html

      # Subir el reporte generado como artefacto
      - name: Upload DAST report
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html

      # Detener y limpiar el contenedor de OWASP ZAP
      - name: Clean up
        run: |
          docker stop zap
          docker rm zap
