name: OWASP ZAP Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      # Configurar el repositorio
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurar Node.js (opcional si necesitas levantar tu aplicación con Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependencias y levantar el servidor
      - name: Install Dependencies
        run: |
          npm install
      - name: Start Server
        run: |
          nohup npm start &
          sleep 10 # Espera a que el servidor inicie

      # Ejecutar OWASP ZAP
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://localhost:3000' # URL de tu aplicación
          rules_file_name: '.zap/rules.json'
          docker_image: 'zaproxy/zap2docker-stable' # Imagen correcta
          cmd_options: '-config api.disablekey=true'

      # Cargar reporte como artefacto
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: owasp-zap-report.html
