name: OWASP ZAP Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      # Clonar el código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Limpiar el sistema Docker
      - name: Clean Docker System
        run: docker system prune -af

      # Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Instalar dependencias y levantar el servidor
      - name: Setup and Start Server
        run: |
          npm install
          nohup npm start &
          sleep 15 # Espera a que el servidor inicie

      # Ejecutar OWASP ZAP
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://localhost:3000' # Cambia según tu aplicación
          cmd_options: '-config api.disablekey=true'

      # Cargar reporte como artefacto
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: owasp-zap-report.html
